apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-learnixelearn-shop-tls
  namespace: default 
spec:
  secretName: tls-secret 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.learnixelearn.shop
  dnsNames:
    - app.learnixelearn.shop
