apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnix-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"  
  tls:
    - hosts:
        - app.learnixelearn.shop
      secretName: tls-secret
  rules:
    - host: app.learnixelearn.shop
      http:
        paths:
          - path: /api/transcode  
            pathType: Prefix
            backend:
              service:
                name: learnix-transcoder
                port:
                  number: 8001
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
